ITEM.name = "Acolyte Sith Lower Armor"
ITEM.description = ""
ITEM.outfitCategory = "legs"
ITEM.uniqueID = "AcoliteS_lower"
ITEM.model = "models/nate159/req/SWTFU/sith_acolyte.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.width = 1
ITEM.height = 1
ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }
ITEM.attribBoosts = {
    ["str"] = 10, 
    ["stm"] = 14,  
	["arm"] = 15,
	["end"] = 13
}

ITEM.pacData = {
	[1] = {
	["children"] = {
		[1] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "9fb5e1e5bf68604caebf68376a09edea",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "spine 1",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[2] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "fc1935597514e433f048ecaebd7d5529",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right thigh",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[3] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "beb7a517724895d9f5b858566cd709ca",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left thigh",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[4] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "3c90697f9fb106c252526205dd56aa44",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left calf",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[5] = {
			["children"] = {
				[1] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "ee0e40a7e839b8c806baf948f1fcbe5e",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "pelvis",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(-5.61474609375, 3.5849452018738, -7.90625),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 17.625,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[2] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "68f5af1ecb92bba0e588ca8d4c379a43",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right thigh",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 85.55,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[3] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "756c483c33ad36456ef0c328e38c8c67",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left calf",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 92.175,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[4] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "a976d072fccbb9b1685463cd6287e9b7",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right foot",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(-10.936935424805, -4.1739258449525e-05, 2.9375094527495e-05),
						["Position"] = Vector(-2.15625, -7.0078125, 8.146484375),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 140.35,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[5] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "f2a74e30d43e2190a2f8d25d2e5b0012",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 83.65,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[6] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "cd1db0f81c76a6e5077365d4aa0be896",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right calf",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 97.8,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[7] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "cc5f8c2bb6ba4b155f5151d4e5a05b4e",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine 1",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 82.475,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[8] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "d24d33616b30d6228ee7ddd2b32081f8",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left foot",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(10.253502845764, -2.0823117665714e-05, -7.213529170258e-05),
						["Position"] = Vector(4.28125, -8.4765625, -9.458984375),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 137.825,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[9] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "02925f9c29ff249c4e34788a50755e6d",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left thigh",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 85.5,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
			},
			["self"] = {
				["Skin"] = 0,
				["UniqueID"] = "1378e3a71bf83a565092a8d785d67110",
				["NoLighting"] = false,
				["AimPartName"] = "",
				["IgnoreZ"] = false,
				["AimPartUID"] = "",
				["Notes"] = "",
				["Materials"] = "",
				["Name"] = "",
				["LevelOfDetail"] = 0,
				["NoTextureFiltering"] = false,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["EyeAngles"] = false,
				["DrawOrder"] = 0,
				["TargetEntityUID"] = "",
				["Alpha"] = 1,
				["Material"] = "",
				["Invert"] = false,
				["ForceObjUrl"] = false,
				["Bone"] = "head",
				["Color"] = Vector(1, 1, 1),
				["AngleOffset"] = Angle(0, 0, 0),
				["BoneMerge"] = true,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["ClassName"] = "model2",
				["NoCulling"] = false,
				["Hide"] = false,
				["Brightness"] = 1,
				["Scale"] = Vector(1, 1, 1),
				["LegacyTransform"] = false,
				["EditorExpand"] = true,
				["Size"] = 0.1,
				["Translucent"] = false,
				["BlendMode"] = "",
				["ModelModifiers"] = "",
				["EyeTargetUID"] = "",
				["Model"] = "models/nate159/req/SWTFU/sith_acolyte.mdl",
			},
		},
		[6] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "54e12db48b7dcfc1d4c50c08523b6076",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "pelvis",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[7] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "20d16b9538c8b103c929ced0dcd459c3",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "spine",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[8] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "1acf59c4daddf387018b7320ea4ce8c4",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right calf",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[9] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "3d09cdf720169476e663ff86196ff7ea",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left foot",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[10] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "35f7e66e5a9e14a503f393ddfaaf9628",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right foot",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "13e0658b7393bf35beed269767f55b3c",
		["Notes"] = "",
		["Hide"] = false,
		["Name"] = "",
		["TargetEntityUID"] = "",
		["EditorExpand"] = true,
		["OwnerName"] = "self",
		["Duplicate"] = false,
		["IsDisturbing"] = false,
		["ModelTracker"] = "models/player/jedi/nautolan.mdl",
		["ClassTracker"] = "player",
		["ClassName"] = "group",
	},
},
[2] = {
	["children"] = {
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "c7c91670a572b63ac9ab9045454016be",
		["Notes"] = "",
		["Hide"] = false,
		["Name"] = "my outfit",
		["TargetEntityUID"] = "",
		["EditorExpand"] = false,
		["OwnerName"] = "self",
		["Duplicate"] = false,
		["IsDisturbing"] = false,
		["ModelTracker"] = "models/player/jedi/nautolan.mdl",
		["ClassTracker"] = "player",
		["ClassName"] = "group",
	},
},

}
