ITEM.name = "Glack Guard Upper Armor"
ITEM.description = ""
ITEM.outfitCategory = "chest"
ITEM.uniqueID = "black_guard_upper_armor"
ITEM.model = "models/nada/tfushadowguard.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.width = 1
ITEM.height = 1
ITEM.iconCam = {
	pos = Vector(62.92, -2.48, 55.19),
	ang = Angle(-3.98, 179.32, 0.05),
	fov = 27.35,
}
ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }

ITEM.pacData = {
	[1] = {
		["children"] = {
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "a435ca48b1dba5ceceda76a3b5e5e7a1",
			["Notes"] = "",
			["Hide"] = false,
			["Name"] = "my outfit",
			["TargetEntityUID"] = "",
			["EditorExpand"] = false,
			["OwnerName"] = "self",
			["Duplicate"] = false,
			["IsDisturbing"] = false,
			["ModelTracker"] = "models/player/sith/human.mdl",
			["ClassTracker"] = "player",
			["ClassName"] = "group",
		},
	},
	[2] = {
		["children"] = {
			[1] = {
				["children"] = {
					[1] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "8434a3144679ab0c8cefe6ba9199a8be",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "spine 2",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 9.775,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[2] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "c0fe93ef571bebc9010a27387affb579",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "left upperarm",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 11.7,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[3] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "c8b4e3306f2584dafbf63eb0b014c7eb",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "left clavicle",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 8.225,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[4] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "83e0a49ca7c5482ad86d242835a2c515",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "spine 4",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 10.725,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[5] = {
						["children"] = {
						},
						["self"] = {
							["Jiggle"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "4890f0349a8cea4209149dbe33a9df25",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "right upperarm",
							["AngleOffset"] = Angle(0, 0, 0),
							["ScaleChildren"] = false,
							["ClassName"] = "bone",
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["MoveChildrenToOrigin"] = false,
							["Size"] = 11.625,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["AlternativeBones"] = false,
							["EyeAngles"] = false,
							["FollowAnglesOnly"] = false,
						},
					},
					[6] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "45cd0885734dfd19e51d1cda0c9331f7",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "right clavicle",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 9.825,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[7] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "83ae554a9f274a928e5a75ed4fc34941",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "head",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 1,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
				},
				["self"] = {
					["Skin"] = 0,
					["UniqueID"] = "24d96015e180a9dcd3d37ee9ff45a7e6",
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Notes"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "head",
					["Color"] = Vector(1, 1, 1),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["ClassName"] = "model2",
					["NoCulling"] = false,
					["Hide"] = false,
					["Brightness"] = 1,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = true,
					["Size"] = 0.1,
					["Translucent"] = false,
					["BlendMode"] = "",
					["ModelModifiers"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/nada/tfushadowguard.mdl",
				},
			},
			[2] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "4cc112bb0c9401421903bf6c7c994200",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "head",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "2591ea3c723ea34c817786ee067801f7",
			["Notes"] = "",
			["Hide"] = false,
			["Name"] = "",
			["TargetEntityUID"] = "",
			["EditorExpand"] = true,
			["OwnerName"] = "self",
			["Duplicate"] = false,
			["IsDisturbing"] = false,
			["ModelTracker"] = "models/player/sith/human.mdl",
			["ClassTracker"] = "player",
			["ClassName"] = "group",
		},
	},
	
}
