ITEM.name = "Blue Guard Armor Gloves"
ITEM.description = ""
ITEM.outfitCategory = "gloves"
ITEM.uniqueID = "black_guard_armor_gloves"
ITEM.model = "models/nada/tfuimperialsenateguard.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }
ITEM.pacData = {
	[1] = {
		["children"] = {
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "b471cf367d2e263acb8f0abd0eb098e4",
			["Notes"] = "",
			["Hide"] = false,
			["Name"] = "my outfit",
			["TargetEntityUID"] = "",
			["EditorExpand"] = false,
			["OwnerName"] = "self",
			["Duplicate"] = false,
			["IsDisturbing"] = false,
			["ModelTracker"] = "models/player/sith/human.mdl",
			["ClassTracker"] = "player",
			["ClassName"] = "group",
		},
	},
	[2] = {
		["children"] = {
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "a3b030ef58bb915fe89f0ad65d410d6a",
			["Notes"] = "",
			["Hide"] = false,
			["Name"] = "",
			["TargetEntityUID"] = "",
			["EditorExpand"] = false,
			["OwnerName"] = "self",
			["Duplicate"] = false,
			["IsDisturbing"] = false,
			["ModelTracker"] = "models/player/sith/human.mdl",
			["ClassTracker"] = "player",
			["ClassName"] = "group",
		},
	},
	[3] = {
		["children"] = {
			[1] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "de0529c7ed8f45e97f76765548fa2793",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "left forearm",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[2] = {
				["children"] = {
					[1] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "e251d4ad7fae6c7bf36c6fe7a93ed97f",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "right forearm",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 91.6,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[2] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "989ccf2d087c357865bc71c28fad6c5e",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "left forearm",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 95.2,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[3] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "c4170a6eeda5be824b7cf7785f024590",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "left hand",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(-0.578125, 0.013671875, 0.2529296875),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 12.725,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[4] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "ea1222021605e1257b525f3415b89a79",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "right hand",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 9.775,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
				},
				["self"] = {
					["Skin"] = 0,
					["UniqueID"] = "d622bafe21dbd039cb06f2b7a7366023",
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Notes"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "head",
					["Color"] = Vector(1, 1, 1),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["ClassName"] = "model2",
					["NoCulling"] = false,
					["Hide"] = false,
					["Brightness"] = 1,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = true,
					["Size"] = 0.1,
					["Translucent"] = false,
					["BlendMode"] = "",
					["ModelModifiers"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/nada/tfushadowguard.mdl",
				},
			},
			[3] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "6dd1fa8467d705b54950c75101036f56",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "left hand",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[4] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "01ded9b4b48a12c0f85131b30246ff2b",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "right forearm",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[5] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "263c683e093946fea917af2a042a1eb5",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "right hand",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "f8b18750966114c629bae3177019e7ef",
			["Notes"] = "",
			["Hide"] = false,
			["Name"] = "my outfit",
			["TargetEntityUID"] = "",
			["EditorExpand"] = true,
			["OwnerName"] = "self",
			["Duplicate"] = false,
			["IsDisturbing"] = false,
			["ModelTracker"] = "models/player/sith/human.mdl",
			["ClassTracker"] = "player",
			["ClassName"] = "group",
		},
	},
	
}
