ITEM.name = "Darth Jadus lower armor"
ITEM.description = ""
ITEM.uniqueID = "dj_lower"
ITEM.outfitCategory = "lower"
ITEM.model = "models/grealms/characters/darthjadus/darthjadus.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.width = 1
ITEM.height = 1
ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }

ITEM.pacData = {
[1] = {
	["children"] = {
		[1] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "8b4779596b2868a2c3d44204e52378eb",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right thigh",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[2] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "c1f312326e08e25eed567c0284a7cb39",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left foot",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[3] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "3b41dd31fafaa27f4961fe1f16d81774",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left thigh",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[4] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "a277f31c507373713d2b55a42a176465",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left calf",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[5] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "e2b8a06c9b65370262ed4740b3674540",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "spine 1",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[6] = {
			["children"] = {
				[1] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "46249b71360d3cf30fd59418defcd22b",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right thigh",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 85.55,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[2] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "32299c8dea3da55b1bb6e72e8e82a269",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left foot",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(10.253502845764, -2.0823117665714e-05, -7.213529170258e-05),
						["Position"] = Vector(4.28125, -8.4765625, -9.458984375),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 137.825,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[3] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "0dc3eca6b220c8bed6e0b5c68625ec3b",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine 1",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 122.75,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[4] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "8bc4a14831972a289d048aa55079dd11",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right foot",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(-10.936935424805, -4.1739258449525e-05, 2.9375094527495e-05),
						["Position"] = Vector(-2.15625, -7.0078125, 8.146484375),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 140.35,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[5] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "cb160df88c006fedcc546892390d9169",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 83.65,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[6] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "924011cfe2253126674105589f67af5b",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left calf",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 92.175,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[7] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "6bacd9863bc7b412b5846f34c560cee9",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "pelvis",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(-5.61474609375, 3.5849452018738, -7.90625),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 17.625,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[8] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "2652c7937c66977fdcab6ab8b6ac1b7a",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left thigh",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 85.5,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[9] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "95e8639ecde4a2e511172726d4ca8130",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right calf",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 97.8,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
			},
			["self"] = {
				["Skin"] = 0,
				["UniqueID"] = "dd29bbd6c55c1162a7971162e176a216",
				["NoLighting"] = false,
				["AimPartName"] = "",
				["IgnoreZ"] = false,
				["AimPartUID"] = "",
				["Notes"] = "",
				["Materials"] = "",
				["Name"] = "",
				["LevelOfDetail"] = 0,
				["NoTextureFiltering"] = false,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["EyeAngles"] = false,
				["DrawOrder"] = 0,
				["TargetEntityUID"] = "",
				["Alpha"] = 1,
				["Material"] = "",
				["Invert"] = false,
				["ForceObjUrl"] = false,
				["Bone"] = "head",
				["Color"] = Vector(1, 1, 1),
				["AngleOffset"] = Angle(0, 0, 0),
				["BoneMerge"] = true,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["ClassName"] = "model2",
				["NoCulling"] = false,
				["Hide"] = false,
				["Brightness"] = 1,
				["Scale"] = Vector(1, 1, 1),
				["LegacyTransform"] = false,
				["EditorExpand"] = true,
				["Size"] = 0.1,
				["Translucent"] = false,
				["BlendMode"] = "",
				["ModelModifiers"] = "",
				["EyeTargetUID"] = "",
				["Model"] = "models/grealms/characters/darthjadus/darthjadus.mdl",
			},
		},
		[7] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "0dac5ddd33a1c1c71c0e155b86a0d4d6",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right calf",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[8] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "8e446234eda9d527835186a5576b9bba",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "spine",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[9] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "826f4cbf8a2edba0f82fa8307bc0c177",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right foot",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[10] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "5ca151fbb094750ed13e42073fb5643d",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "pelvis",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "ba497625f4e6b02885852ed0652d4b5d",
		["Notes"] = "",
		["Hide"] = false,
		["Name"] = "",
		["TargetEntityUID"] = "",
		["EditorExpand"] = true,
		["OwnerName"] = "self",
		["Duplicate"] = false,
		["IsDisturbing"] = false,
		["ModelTracker"] = "models/player/jedi/nautolan.mdl",
		["ClassTracker"] = "player",
		["ClassName"] = "group",
	},
},
[2] = {
	["children"] = {
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "086e4c3965fbfc7cc303c4f0539a467d",
		["Notes"] = "",
		["Hide"] = false,
		["Name"] = "my outfit",
		["TargetEntityUID"] = "",
		["EditorExpand"] = false,
		["OwnerName"] = "self",
		["Duplicate"] = false,
		["IsDisturbing"] = false,
		["ModelTracker"] = "models/player/jedi/nautolan.mdl",
		["ClassTracker"] = "player",
		["ClassName"] = "group",
	},
},

}
