ITEM.name = "Darth Jadus upper armor"
ITEM.description = ""
ITEM.uniqueID = "dj_upper"
ITEM.outfitCategory = "upper"
ITEM.model = "models/grealms/characters/darthjadus/darthjadus.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.width = 1
ITEM.height = 1
ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }

ITEM.pacData = {
[1] = {
	["children"] = {
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "9a561de6ec26d3cf6474a48e6c9a6100",
		["Notes"] = "",
		["Hide"] = false,
		["Name"] = "my outfit",
		["TargetEntityUID"] = "",
		["EditorExpand"] = false,
		["OwnerName"] = "self",
		["Duplicate"] = false,
		["IsDisturbing"] = false,
		["ModelTracker"] = "models/player/jedi/nautolan.mdl",
		["ClassTracker"] = "player",
		["ClassName"] = "group",
	},
},
[2] = {
	["children"] = {
		[1] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "1deb5f317e430647bddb5f8b095f7ac3",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left upperarm",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[2] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "1c3233f72f5ba1f100ef8d9061444a4e",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left forearm",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[3] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "d178a74c6b272e8a87663720fad65ec2",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right forearm",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[4] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "41cfffe3fc42f1e88abce2287772c4ce",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "spine 4",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[5] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "66bf37610e8822a31031da288fad7047",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "spine 2",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[6] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "5cc2bd5019b2c72883dbfb3a58eda890",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right clavicle",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[7] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "e5a88ec0b076e418730524d096475d04",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right upperarm",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[8] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "7dd5154f400be0ecf0bba8cbfad00d04",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left clavicle",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[9] = {
			["children"] = {
				[1] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "8b64d4130c39b7087df4498e5257813b",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine 4",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 109.675,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[2] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "a950e36b09112e3ee4126d4fcfc9459d",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left hand",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 12.575,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[3] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "c0194e8b9a050c1a5f6aa1a0a8942827",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left upperarm",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 112.2,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[4] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "aedba31661c98921637aa753f0a89fe0",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine 2",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 93,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[5] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "77670e73c4be106435a593f23de3c076",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right hand",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(9.7650354291545e-06, 0.33449673652649, -1.2806605809601e-05),
						["Position"] = Vector(-0.001953125, -0.4306640625, 0.037109375),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 10.8,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[6] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "d878f39a4ce8542511d885b9df0ab206",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left forearm",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 87.6,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[7] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "75541a0957077e23e85397cc8ab2a98b",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right upperarm",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 111.3,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[8] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "5b459c29cad3c2cfd8c7d48d1cce2fdb",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "head",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 0.1,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[9] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "09245d30d4134715cc0d8e2808eeed42",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left clavicle",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 94.225,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[10] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "470554c7a7e93a5987d77263fdfd22ea",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right forearm",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 79.25,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[11] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "cfdce5e41dab9d24c55218b18c8a706e",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right clavicle",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 88.15,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
			},
			["self"] = {
				["Skin"] = 0,
				["UniqueID"] = "ddec8030c39f1ef85a298f3e8f69d1a9",
				["NoLighting"] = false,
				["AimPartName"] = "",
				["IgnoreZ"] = false,
				["AimPartUID"] = "",
				["Notes"] = "",
				["Materials"] = "",
				["Name"] = "",
				["LevelOfDetail"] = 0,
				["NoTextureFiltering"] = false,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["EyeAngles"] = false,
				["DrawOrder"] = 0,
				["TargetEntityUID"] = "",
				["Alpha"] = 1,
				["Material"] = "",
				["Invert"] = false,
				["ForceObjUrl"] = false,
				["Bone"] = "head",
				["Color"] = Vector(1, 1, 1),
				["AngleOffset"] = Angle(0, 0, 0),
				["BoneMerge"] = true,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["ClassName"] = "model2",
				["NoCulling"] = false,
				["Hide"] = false,
				["Brightness"] = 1,
				["Scale"] = Vector(1, 1, 1),
				["LegacyTransform"] = false,
				["EditorExpand"] = true,
				["Size"] = 0.1,
				["Translucent"] = false,
				["BlendMode"] = "",
				["ModelModifiers"] = "",
				["EyeTargetUID"] = "",
				["Model"] = "models/grealms/characters/darthjadus/darthjadus.mdl",
			},
		},
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "890693382ada8f89128dd9491bfc7f3c",
		["Notes"] = "",
		["Hide"] = false,
		["Name"] = "",
		["TargetEntityUID"] = "",
		["EditorExpand"] = true,
		["OwnerName"] = "self",
		["Duplicate"] = false,
		["IsDisturbing"] = false,
		["ModelTracker"] = "models/player/jedi/nautolan.mdl",
		["ClassTracker"] = "player",
		["ClassName"] = "group",
	},
},


}
