ITEM.name = "Jedi Korean Chicken cape"
ITEM.description = ""
ITEM.outfitCategory = "cape"
ITEM.uniqueID = "jedi_korean_chicken_cape"
ITEM.model = "models/gonzo/jedikoreanchicken/jedikoreanchicken.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }

ITEM.pacData = {
    [1] = {
        ["children"] = {
            [1] = {
                ["children"] = {
                    [1] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "ef010c7bb720eb1824b266bcb3244d00",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "spine 4",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 12.425,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                },
                ["self"] = {
                    ["Skin"] = 0,
                    ["UniqueID"] = "62b3bd552c570f00efe0b974fd66a8a5",
                    ["NoLighting"] = false,
                    ["AimPartName"] = "",
                    ["IgnoreZ"] = false,
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Materials"] = "",
                    ["Name"] = "",
                    ["LevelOfDetail"] = 0,
                    ["NoTextureFiltering"] = false,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["EyeAngles"] = false,
                    ["DrawOrder"] = 0,
                    ["TargetEntityUID"] = "",
                    ["Alpha"] = 1,
                    ["Material"] = "",
                    ["Invert"] = false,
                    ["ForceObjUrl"] = false,
                    ["Bone"] = "left upperarm",
                    ["Color"] = Vector(1, 1, 1),
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["BoneMerge"] = true,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["ClassName"] = "model2",
                    ["NoCulling"] = false,
                    ["Hide"] = false,
                    ["Brightness"] = 1,
                    ["Scale"] = Vector(1, 1, 1),
                    ["LegacyTransform"] = false,
                    ["EditorExpand"] = true,
                    ["Size"] = 0.1,
                    ["Translucent"] = false,
                    ["BlendMode"] = "",
                    ["ModelModifiers"] = "",
                    ["EyeTargetUID"] = "",
                    ["Model"] = "models/gonzo/jedikoreanchicken/jedikoreanchicken.mdl",
                },
            },
            [2] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "acdf8af0b873026f74172e0303bfde9d",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "spine 4",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
        },
        ["self"] = {
            ["DrawOrder"] = 0,
            ["UniqueID"] = "14d00d4e031c10e40492bea715369d1a",
            ["Notes"] = "",
            ["Hide"] = false,
            ["Name"] = "",
            ["TargetEntityUID"] = "",
            ["EditorExpand"] = true,
            ["OwnerName"] = "self",
            ["Duplicate"] = false,
            ["IsDisturbing"] = false,
            ["ModelTracker"] = "models/player/jedi/human.mdl",
            ["ClassTracker"] = "player",
            ["ClassName"] = "group",
        },
    },    
}
