ITEM.name = "Luke Skywaker legs"
ITEM.description = ""
ITEM.uniqueID = "luke_skywaker_legs"
ITEM.outfitCategory = "legs"
ITEM.model = "models/player/luke_skywalker.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }
ITEM.pacData = {
	[1] = {
		["children"] = {
			[1] = {
				["children"] = {
					[1] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "000c30c69d5ee9e9d23de909d1a0184466fd785a24900e1b5c66b97d2f74abb3",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "spine",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 100,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[2] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "04e29587a212c7516044b43001b64fb1123abde748ebbe56f9a84e71a13d4b42",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "left thigh",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 100,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[3] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "a11e8aa06b4040cf9af484884dcf77dbca2108535634e5ea5fe05728a6ae7f8f",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "right calf",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 100,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[4] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "6f4ffded50c986163407afdd06be518cfe39365f9032909442f87bf0ded16e0e",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "right foot",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 100,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[5] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "cd584548d4acdd8cd5045de035758e3aff528c0263a7cd6477891319b385267c",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "right thigh",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 100,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[6] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "f903023af9bc6d6957e0edeeb5aa24d4a69ce91774eeaf7a2f0ce4d409bf9b2b",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "spine 1",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 15.15,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[7] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "84abe981b669f6bcb0a4a44b07e8d7fca2abd9e0f0964fe51f1974026a0035df",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "left calf",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 100,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[8] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "a9deb8b4fd7966f76db19c9a81fbaa3d405162f30b2e710ea87dbbc544d0dd4d",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "pelvis",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 16.85,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[9] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "82f0d993df35ee9deb28dae9f1321aa7935463477bbdd373c4a4efaead867b15",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "left foot",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 100,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
				},
				["self"] = {
					["Skin"] = 0,
					["UniqueID"] = "76b1274abca3f43f9f0bfb6b497e7e43865e642e8c4ea35f10fa3c9029564d12",
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Notes"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "head",
					["Color"] = Vector(1, 1, 1),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["ClassName"] = "model2",
					["NoCulling"] = false,
					["Hide"] = false,
					["Brightness"] = 1,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = true,
					["Size"] = 0.1,
					["Translucent"] = false,
					["BlendMode"] = "",
					["ModelModifiers"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/player/luke_skywalker.mdl",
				},
			},
			[2] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "e8b1bfb5e8dfb67140efdc7e23c974e94e5c80b18b40c9edf8c13cffb8a91539",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "left foot",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[3] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "834ecd52b15cb31201ade7eb7836884448f57b67d957a1896cf76e213c37ecbd",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "right calf",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[4] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "f954d8762386f7ecaf6cc8b93ff5e62add42db16944a95702ff15668d5e5cc61",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "right foot",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[5] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "199307cf91abb08eadc9d25d7cb652cc6a3d33a3b7afae89c40423d36ca39f95",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "left thigh",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[6] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "2267cde6afcba6fc8e397a2cde9c9e078cbd5ef1f56a0c36e59779830d266fd0",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "right thigh",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[7] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "ab9fd8eab84299fafc9ee9f4a3cfe4311efdfc8800c850bc64f5f1fb2cd15284",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "left calf",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[8] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "2699f27b7c54bcc987fbe4c83c3fe62822b58e666bceb06237eb5c4f9a85801c",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "spine",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[9] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "c8c48a8c4b869f31da842a9033440349c0c653df1f59f4cdd47b723cacdd2bfd",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "pelvis",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "48fa9db82913a8b9991b82e69d9e50acd45e3460928ca51425054e0a3af56c0d",
			["Notes"] = "",
			["Hide"] = false,
			["Name"] = "",
			["TargetEntityUID"] = "",
			["EditorExpand"] = true,
			["OwnerName"] = "self",
			["Duplicate"] = false,
			["IsDisturbing"] = false,
			["ModelTracker"] = "models/player/sith/pantoran.mdl",
			["ClassTracker"] = "player",
			["ClassName"] = "group",
		},
	},	
}
