ITEM.name = "Red Guard Lower Armor"
ITEM.description = ""
ITEM.outfitCategory = "legs"
ITEM.uniqueID = "red_guard_lower_armor"
ITEM.model = "models/nada/tfuroyalguard.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.width = 1
ITEM.height = 1
ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }
ITEM.pacData = {
	[1] = {
		["children"] = {
			[1] = {
				["children"] = {
					[1] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "ec3719bbd12d5889a573d5ba213f07d7",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "spine 1",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 82.475,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[2] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "ae17dff783f409da830eacf44f2d26dc",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "pelvis",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(-5.61474609375, 3.5849452018738, -7.90625),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 17.625,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[3] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "ce49419101b9b3f73402223d05907bcc",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "right calf",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 97.8,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[4] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "287579f57a70b25179297d9cbf74254f",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "right foot",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(-10.936935424805, -4.1739258449525e-05, 2.9375094527495e-05),
							["Position"] = Vector(-2.15625, -7.0078125, 8.146484375),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 140.35,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[5] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "507c3714bea03f7ad1a2eae932633fac",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "spine",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 83.65,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[6] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "566c78fe1d122ff9d4d6470468943ee2",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "left thigh",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 85.5,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[7] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "fdc746fede8a95ad6867cbc13e31d541",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "left calf",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 92.175,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[8] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "8694a76ef4b371ebde6ce93bbbd0971e",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "right thigh",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(0, 0, 0),
							["Position"] = Vector(0, 0, 0),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 85.55,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
					[9] = {
						["children"] = {
						},
						["self"] = {
							["FollowAnglesOnly"] = false,
							["DrawOrder"] = 0,
							["UniqueID"] = "5d2dd4a333f3b9da910d524b896388bf",
							["TargetEntityUID"] = "",
							["AimPartName"] = "",
							["FollowPartUID"] = "",
							["Bone"] = "left foot",
							["InvertHideMesh"] = false,
							["ScaleChildren"] = false,
							["MoveChildrenToOrigin"] = false,
							["Angles"] = Angle(10.253502845764, -2.0823117665714e-05, -7.213529170258e-05),
							["Position"] = Vector(4.28125, -8.4765625, -9.458984375),
							["AimPartUID"] = "",
							["Notes"] = "",
							["Hide"] = false,
							["Name"] = "",
							["Scale"] = Vector(1, 1, 1),
							["EditorExpand"] = false,
							["AngleOffset"] = Angle(0, 0, 0),
							["Size"] = 137.825,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "bone3",
							["EyeAngles"] = false,
							["HideMesh"] = false,
						},
					},
				},
				["self"] = {
					["Skin"] = 0,
					["UniqueID"] = "b880e87dda0b6a7a8def5194c6455f44",
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Notes"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "head",
					["Color"] = Vector(1, 1, 1),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["ClassName"] = "model2",
					["NoCulling"] = false,
					["Hide"] = false,
					["Brightness"] = 1,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = true,
					["Size"] = 0.1,
					["Translucent"] = false,
					["BlendMode"] = "",
					["ModelModifiers"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/nada/tfuroyalguard.mdl",
				},
			},
			[2] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "643e77b9d8eb37fde1d268455d2ea9b6",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "spine 1",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[3] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "1f3f154807585599f1c21886b71a8b8e",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "left thigh",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[4] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "a8c06b72649021e19b50713dd2a31293",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "left calf",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[5] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "123eda42a31c12d827120740957304f5",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "pelvis",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[6] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "e2bf7a0513dfd61bd963d24b8fddfdcd",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "right foot",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[7] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "f3e00192e5a1f276f1891e74e047e103",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "right calf",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[8] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "6be8555fbd0e3b0966dd5cf78d6ff194",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "spine",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[9] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "a7a3dd3fd3cb33a35e12d9f90a94cab1",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "right thigh",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
			[10] = {
				["children"] = {
				},
				["self"] = {
					["FollowAnglesOnly"] = false,
					["DrawOrder"] = 0,
					["UniqueID"] = "4955503768e580bd6f3929766cb0de45",
					["TargetEntityUID"] = "",
					["AimPartName"] = "",
					["FollowPartUID"] = "",
					["Bone"] = "left foot",
					["InvertHideMesh"] = false,
					["ScaleChildren"] = false,
					["MoveChildrenToOrigin"] = false,
					["Angles"] = Angle(0, 0, 0),
					["Position"] = Vector(0, 0, 0),
					["AimPartUID"] = "",
					["Notes"] = "",
					["Hide"] = false,
					["Name"] = "",
					["Scale"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["AngleOffset"] = Angle(0, 0, 0),
					["Size"] = 0.1,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["ClassName"] = "bone3",
					["EyeAngles"] = false,
					["HideMesh"] = false,
				},
			},
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "fd84439da3bb3b4acf088cb3808d0f67",
			["Notes"] = "",
			["Hide"] = false,
			["Name"] = "",
			["TargetEntityUID"] = "",
			["EditorExpand"] = true,
			["OwnerName"] = "self",
			["Duplicate"] = false,
			["IsDisturbing"] = false,
			["ModelTracker"] = "models/player/sith/human.mdl",
			["ClassTracker"] = "player",
			["ClassName"] = "group",
		},
	},
	[2] = {
		["children"] = {
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "83323ac6586cf729c3bb12c6d741c623",
			["Notes"] = "",
			["Hide"] = false,
			["Name"] = "my outfit",
			["TargetEntityUID"] = "",
			["EditorExpand"] = false,
			["OwnerName"] = "self",
			["Duplicate"] = false,
			["IsDisturbing"] = false,
			["ModelTracker"] = "models/player/sith/human.mdl",
			["ClassTracker"] = "player",
			["ClassName"] = "group",
		},
	},
	
}
