ITEM.name = "Sith Trooper Red Lower Armor"
ITEM.description = ""
ITEM.outfitCategory = "legs"
ITEM.uniqueID = "sith_trooper_red_lower_armor"
ITEM.Base = "base_pacmmooutfit"

ITEM.model = "models/player/cheddar/swtor/sith_empire/trooper/sith_trooper_siege.mdl"
ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }

ITEM.pacData = {
    [1] = {
        ["children"] = {
            [1] = {
                ["children"] = {
                    [1] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "3e4a7db7ad131f1182af8e9d6d918e1c",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "pelvis",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 10,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [2] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "b225c3c26d0e82f0dd3145c48b15b29a",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left thigh",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [3] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "603c88cd23fed1d3532bf32ba4269b59",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left calf",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [4] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "8302b5207cc0d1fdbc5edae04e7d8dbc",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left foot",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [5] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "b210c841f976fc2294b81e24e3757c63",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "spine",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [6] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "1aeb84f4d8788082937dcdf7e287595e",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right calf",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [7] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "eda9d1363eb7bff42f994079394d437b",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right foot",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [8] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "544af69e8f4542ab067d9be2a9b20cc0",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right thigh",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [9] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "69efa1bf6fc9bddb80ace1d4c2108ae0",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "spine 1",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0.994873046875, -0.49609375, -0.00726318359375),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 9,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                },
                ["self"] = {
                    ["Skin"] = 0,
                    ["UniqueID"] = "7b912d1d5dc8935dcdb3a310fb13f428",
                    ["NoLighting"] = false,
                    ["AimPartName"] = "",
                    ["IgnoreZ"] = false,
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Materials"] = "",
                    ["Name"] = "",
                    ["LevelOfDetail"] = 0,
                    ["NoTextureFiltering"] = false,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["EyeAngles"] = false,
                    ["DrawOrder"] = 0,
                    ["TargetEntityUID"] = "",
                    ["Alpha"] = 1,
                    ["Material"] = "",
                    ["Invert"] = false,
                    ["ForceObjUrl"] = false,
                    ["Bone"] = "head",
                    ["Color"] = Vector(1, 1, 1),
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["BoneMerge"] = true,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["ClassName"] = "model2",
                    ["NoCulling"] = false,
                    ["Hide"] = false,
                    ["Brightness"] = 1,
                    ["Scale"] = Vector(1, 1, 1),
                    ["LegacyTransform"] = false,
                    ["EditorExpand"] = true,
                    ["Size"] = 0.1,
                    ["Translucent"] = false,
                    ["BlendMode"] = "",
                    ["ModelModifiers"] = "",
                    ["EyeTargetUID"] = "",
                    ["Model"] = "models/player/cheddar/swtor/sith_empire/trooper/sith_trooper_siege.mdl",
                },
            },
            [2] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "f2c46f2ac92e8485db70b4a586b0140d",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right foot",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [3] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "8bd6bbd26e9e9c46774db7940dce47a5",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "spine",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [4] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "9b429080ef919a9559a6eef0cd42a521",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left thigh",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [5] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "93404ca82ed09459ad603b1561cc69e6",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right calf",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [6] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "23922c081269472efdee7cd0c5bb0899",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left foot",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [7] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "f926d31c68deff85b9dadb8bfec3f90b",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right thigh",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [8] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "9adae642bdad2858d96d3bb99b1b1c48",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left calf",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [9] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "bbfac0c723d6cb2cf6a2e809986e0ddf",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "pelvis",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
        },
        ["self"] = {
            ["DrawOrder"] = 0,
            ["UniqueID"] = "3d50394692f669e4542535a2acb84aae",
            ["Notes"] = "",
            ["Hide"] = false,
            ["Name"] = "",
            ["TargetEntityUID"] = "",
            ["EditorExpand"] = true,
            ["OwnerName"] = "self",
            ["Duplicate"] = false,
            ["IsDisturbing"] = false,
            ["ModelTracker"] = "models/player/jedi/human.mdl",
            ["ClassTracker"] = "player",
            ["ClassName"] = "group",
        },
    },       
}
