ITEM.name = "Sith Trooper Black Upper Armor"
ITEM.description = ""
ITEM.outfitCategory = "chest"
ITEM.uniqueID = "sith_trooper_black_chest"
ITEM.model = "models/player/cheddar/swtor/sith_empire/trooper/sith_trooper_assault.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }

ITEM.pacData = {
    [1] = {
        ["children"] = {
            [1] = {
                ["children"] = {
                    [1] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "a9f5f2f24d745a1d08c85b03b7d696b4",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "neck",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [2] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "c101334ef78263bf01a1024a5586e440",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right hand",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 11,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [3] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "eec48a8757a0a69245cc650ed73ce713",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right clavicle",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [4] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "c48cdeadd5d27bc000ae81d1b4ebe138",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left upperarm",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [5] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "373bfdcb7f86d4046dec102db6580215",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left forearm",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [6] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "ed9138368841d6dad56ee1e47ccd2607",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "spine 2",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [7] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "d34c9de70a2ad96f7da5d695aaa1f552",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "spine 4",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [8] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "f6abe0d33e3cfc222251fa11b46d8c1d",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right upperarm",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [9] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "1f21e7330bd07b165bb456a88a84a231",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left hand",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 11,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [10] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "26ed864ff2ffc8e8cc16ae8d5be60421",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right forearm",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [11] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "47eb51e90627ea746aca49051179957e",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left clavicle",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [12] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "86db72a31f8db9b3a5f613bcd41b1aac",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "spine 1",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                },
                ["self"] = {
                    ["Skin"] = 0,
                    ["UniqueID"] = "3c3783528263dddfb978c29daebf8111",
                    ["NoLighting"] = false,
                    ["AimPartName"] = "",
                    ["IgnoreZ"] = false,
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Materials"] = "",
                    ["Name"] = "",
                    ["LevelOfDetail"] = 0,
                    ["NoTextureFiltering"] = false,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["EyeAngles"] = false,
                    ["DrawOrder"] = 0,
                    ["TargetEntityUID"] = "",
                    ["Alpha"] = 1,
                    ["Material"] = "",
                    ["Invert"] = false,
                    ["ForceObjUrl"] = false,
                    ["Bone"] = "head",
                    ["Color"] = Vector(1, 1, 1),
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["BoneMerge"] = true,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["ClassName"] = "model2",
                    ["NoCulling"] = false,
                    ["Hide"] = false,
                    ["Brightness"] = 1,
                    ["Scale"] = Vector(1, 1, 1),
                    ["LegacyTransform"] = false,
                    ["EditorExpand"] = true,
                    ["Size"] = 0.1,
                    ["Translucent"] = false,
                    ["BlendMode"] = "",
                    ["ModelModifiers"] = "",
                    ["EyeTargetUID"] = "",
                    ["Model"] = "models/player/cheddar/swtor/sith_empire/trooper/sith_trooper_assault.mdl",
                },
            },
            [2] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "b4da774262a8a60559bb9b5fa2a4dae9",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right hand",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [3] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "e4deea5143793083ae2aa25006b115c5",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "spine 2",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [4] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "bef46c0d7ef5db2a1acb2685a8130b56",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "spine 4",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [5] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "b96b5bbee38fb859be96246f1bbfcb74",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right forearm",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [6] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "e70f5f4b465bc1c67f238030b975250e",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right upperarm",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [7] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "1258357612e6f6082e605da191b21ba5",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "neck",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [8] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "f59fe7281d21458c9f13f91f6fed74c5",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right clavicle",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [9] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "6e4eed98e7f26a526f6dd8f6f787daa7",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left clavicle",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [10] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "4a8e05b610d48f430f4daf9fa630cacf",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "spine 1",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [11] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "5e2370f8d8bd3777cd78eabc7e6c132f",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left upperarm",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [12] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "86d506962ad20da92635042dd09e9a68",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left forearm",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [13] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "fff042379873f8dbe158ed3837a9c9fb",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left hand",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [14] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "9b30580d388825d3021cc662a97012d5",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "head",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(-1.36474609375, -0.310546875, -0.24261474609375),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
        },
        ["self"] = {
            ["DrawOrder"] = 0,
            ["UniqueID"] = "8f8491c8b5c9715b3060431493d7a09e",
            ["Notes"] = "",
            ["Hide"] = false,
            ["Name"] = "",
            ["TargetEntityUID"] = "",
            ["EditorExpand"] = true,
            ["OwnerName"] = "self",
            ["Duplicate"] = false,
            ["IsDisturbing"] = false,
            ["ModelTracker"] = "models/player/jedi/human.mdl",
            ["ClassTracker"] = "player",
            ["ClassName"] = "group",
        },
    },    
}
