ITEM.name = "Shilen Revamped upper armor"
ITEM.description = ""
ITEM.uniqueID = "she_upper"
ITEM.outfitCategory = "upper"
ITEM.model = "models/player/swtor/arsenic/shilen2/ShilenRevamped.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.Base = "base_pacmmooutfit"

ITEM.width = 1
ITEM.height = 1
ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }

ITEM.pacData = {
[1] = {
	["children"] = {
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "a633e3e9cae31dad56c2463fe0863cfe",
		["Notes"] = "",
		["Hide"] = false,
		["Name"] = "my outfit",
		["TargetEntityUID"] = "",
		["EditorExpand"] = false,
		["OwnerName"] = "self",
		["Duplicate"] = false,
		["IsDisturbing"] = false,
		["ModelTracker"] = "models/player/jedi/nautolan.mdl",
		["ClassTracker"] = "player",
		["ClassName"] = "group",
	},
},
[2] = {
	["children"] = {
		[1] = {
			["children"] = {
				[1] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "1e60fc0ae8977d407d6c914dc5b93651",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left clavicle",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 8.225,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[2] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "0abbb3dd2d270c025890278db6e2948e",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine 2",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 9.775,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[3] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "962b2efed7e96ded53c2e26fe6c9552b",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left upperarm",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 11.7,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[4] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "c4a0d8c4da02e46c3d8b252c4f9518f1",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine 4",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 10.725,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[5] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "f714f198b16fc0929416289ed326d735",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "head",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 1,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[6] = {
					["children"] = {
					},
					["self"] = {
						["Jiggle"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "da5d40cd21951d52d36ae37ec2ec1be9",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right upperarm",
						["AngleOffset"] = Angle(0, 0, 0),
						["ScaleChildren"] = false,
						["ClassName"] = "bone",
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["MoveChildrenToOrigin"] = false,
						["Size"] = 11.625,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AlternativeBones"] = false,
						["EyeAngles"] = false,
						["FollowAnglesOnly"] = false,
					},
				},
				[7] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "6a82f3413f87df7431ee79a98561b35f",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right clavicle",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 9.825,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
			},
			["self"] = {
				["Skin"] = 0,
				["UniqueID"] = "f849d4425db43c7292d11bd056b52207",
				["NoLighting"] = false,
				["AimPartName"] = "",
				["IgnoreZ"] = false,
				["AimPartUID"] = "",
				["Notes"] = "",
				["Materials"] = "",
				["Name"] = "",
				["LevelOfDetail"] = 0,
				["NoTextureFiltering"] = false,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["EyeAngles"] = false,
				["DrawOrder"] = 0,
				["TargetEntityUID"] = "",
				["Alpha"] = 1,
				["Material"] = "",
				["Invert"] = false,
				["ForceObjUrl"] = false,
				["Bone"] = "head",
				["Color"] = Vector(1, 1, 1),
				["AngleOffset"] = Angle(0, 0, 0),
				["BoneMerge"] = true,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["ClassName"] = "model2",
				["NoCulling"] = false,
				["Hide"] = false,
				["Brightness"] = 1,
				["Scale"] = Vector(1, 1, 1),
				["LegacyTransform"] = false,
				["EditorExpand"] = true,
				["Size"] = 0.1,
				["Translucent"] = false,
				["BlendMode"] = "",
				["ModelModifiers"] = "",
				["EyeTargetUID"] = "",
				["Model"] = "models/player/swtor/arsenic/shilen2/ShilenRevamped.mdl",
			},
		},
		[2] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "44db3e468d14691ac575dc235d0652f9",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "head",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(-0.0665283203125, 0, 0.0009765625),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 1.2,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "88e52706e958cafd6920a525f2bb91e5",
		["Notes"] = "",
		["Hide"] = false,
		["Name"] = "",
		["TargetEntityUID"] = "",
		["EditorExpand"] = true,
		["OwnerName"] = "self",
		["Duplicate"] = false,
		["IsDisturbing"] = false,
		["ModelTracker"] = "models/player/jedi/nautolan.mdl",
		["ClassTracker"] = "player",
		["ClassName"] = "group",
	},
},



}
