ITEM.name = "Shilen Revamped lower armor"
ITEM.description = ""
ITEM.uniqueID = "she_lower"
ITEM.outfitCategory = "lower"
ITEM.model = "models/player/swtor/arsenic/shilen2/ShilenRevamped.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.width = 1
ITEM.height = 1
ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }
ITEM.pacData = {
[1] = {
	["children"] = {
		[1] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "bb5ba80bfb071d7c164c9c9663826c3d",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "spine 1",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[2] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "d6d175996de0f8e0079e888530bf492d",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right thigh",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[3] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "dfeb9be090f909bbe387a8123285219b",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left thigh",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[4] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "3384e6b100b383b13386ff147674e230",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left calf",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[5] = {
			["children"] = {
				[1] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "d2b676c3267daad08c5cf34de6406829",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "pelvis",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(-5.61474609375, 3.5849452018738, -7.90625),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 17.625,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[2] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "ca5524e60acbab49528ca888b332b76c",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right thigh",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 85.55,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[3] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "3b5be32bd8b5b3716eb8252d60d65314",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left calf",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 92.175,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[4] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "1868c84c822780d77b138d294deaa743",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right foot",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(-10.936935424805, -4.1739258449525e-05, 2.9375094527495e-05),
						["Position"] = Vector(-2.15625, -7.0078125, 8.146484375),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 140.35,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[5] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "f6783473d5ac74f07550ac22697668a6",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 83.65,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[6] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "abf8c1d45f99f3f6da2c48ca901ec469",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right calf",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 97.8,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[7] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "d8ee7d15dc5fe9929c8fcff3b11470fa",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine 1",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 82.475,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[8] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "13bd17da80148e57ee7762e89883cde3",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left foot",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(10.253502845764, -2.0823117665714e-05, -7.213529170258e-05),
						["Position"] = Vector(4.28125, -8.4765625, -9.458984375),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 137.825,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[9] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["UniqueID"] = "e32d9248a1942b99b12d8d4ba8b74241",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left thigh",
						["InvertHideMesh"] = false,
						["ScaleChildren"] = false,
						["MoveChildrenToOrigin"] = false,
						["Angles"] = Angle(0, 0, 0),
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Notes"] = "",
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["Size"] = 85.5,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "bone3",
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
			},
			["self"] = {
				["Skin"] = 0,
				["UniqueID"] = "6fefed0afd75ef585c470247a689cdc1",
				["NoLighting"] = false,
				["AimPartName"] = "",
				["IgnoreZ"] = false,
				["AimPartUID"] = "",
				["Notes"] = "",
				["Materials"] = "",
				["Name"] = "",
				["LevelOfDetail"] = 0,
				["NoTextureFiltering"] = false,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["EyeAngles"] = false,
				["DrawOrder"] = 0,
				["TargetEntityUID"] = "",
				["Alpha"] = 1,
				["Material"] = "",
				["Invert"] = false,
				["ForceObjUrl"] = false,
				["Bone"] = "head",
				["Color"] = Vector(1, 1, 1),
				["AngleOffset"] = Angle(0, 0, 0),
				["BoneMerge"] = true,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["ClassName"] = "model2",
				["NoCulling"] = false,
				["Hide"] = false,
				["Brightness"] = 1,
				["Scale"] = Vector(1, 1, 1),
				["LegacyTransform"] = false,
				["EditorExpand"] = true,
				["Size"] = 0.1,
				["Translucent"] = false,
				["BlendMode"] = "",
				["ModelModifiers"] = "",
				["EyeTargetUID"] = "",
				["Model"] = "models/player/swtor/arsenic/shilen2/ShilenRevamped.mdl",
			},
		},
		[6] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "2598b21b8802cf518f823ad04617c950",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "pelvis",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[7] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "b7abe74aa00694460e35b0f5fb4df745",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "spine",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[8] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "adb4dcceaa4074503213dd93e283c92b",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right calf",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[9] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "7b197dc7965390bcec7a0375724a1a62",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "left foot",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
		[10] = {
			["children"] = {
			},
			["self"] = {
				["FollowAnglesOnly"] = false,
				["DrawOrder"] = 0,
				["UniqueID"] = "cfd378f1fec72b6aee1589ae3f7088ca",
				["TargetEntityUID"] = "",
				["AimPartName"] = "",
				["FollowPartUID"] = "",
				["Bone"] = "right foot",
				["InvertHideMesh"] = false,
				["ScaleChildren"] = false,
				["MoveChildrenToOrigin"] = false,
				["Angles"] = Angle(0, 0, 0),
				["Position"] = Vector(0, 0, 0),
				["AimPartUID"] = "",
				["Notes"] = "",
				["Hide"] = false,
				["Name"] = "",
				["Scale"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["AngleOffset"] = Angle(0, 0, 0),
				["Size"] = 0.1,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["ClassName"] = "bone3",
				["EyeAngles"] = false,
				["HideMesh"] = false,
			},
		},
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "6ad4ec539d7af22c56f390f97feae945",
		["Notes"] = "",
		["Hide"] = false,
		["Name"] = "",
		["TargetEntityUID"] = "",
		["EditorExpand"] = true,
		["OwnerName"] = "self",
		["Duplicate"] = false,
		["IsDisturbing"] = false,
		["ModelTracker"] = "models/player/jedi/nautolan.mdl",
		["ClassTracker"] = "player",
		["ClassName"] = "group",
	},
},
[2] = {
	["children"] = {
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "c02f7fae387b23c7adc2694455adafbc",
		["Notes"] = "",
		["Hide"] = false,
		["Name"] = "my outfit",
		["TargetEntityUID"] = "",
		["EditorExpand"] = false,
		["OwnerName"] = "self",
		["Duplicate"] = false,
		["IsDisturbing"] = false,
		["ModelTracker"] = "models/player/jedi/nautolan.mdl",
		["ClassTracker"] = "player",
		["ClassName"] = "group",
	},
},

}
