ITEM.name = "Zakuul Knight Lower Armor"
ITEM.description = ""
ITEM.outfitCategory = "chest"
ITEM.uniqueID = "zakuul_knight_lower_armor"
ITEM.model = "models/player/valley/zakuul/zakuul_knight.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }

ITEM.pacData = {
    [1] = {
        ["children"] = {
            [1] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "4961e154c9ddf0a417f216d0df4181232aabe0f120333f03f50bd2ae84152094",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left calf",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [2] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "aca0c854d00d3da90077983ea9ffd63cd630a6469fdf19706d7f895ec9af8f76",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left foot",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [3] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "0578d8ed858355fa2d79b4c86255ef101feacb180de017ef88af313af9a78b9d",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right foot",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [4] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "e5eb8cfcddceac005830a05decaef91e6fc24f5d3f966e817f02f03b70970dc1",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right thigh",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [5] = {
                ["children"] = {
                    [1] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "f2b8b95af3df68b3499f3577d3aca8a37e89dc334459c03435d218bea5d2e973",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "pelvis",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(-2.03125, -0.66987752914429, 3.328125),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 17,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [2] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "97cd399909cb2919fd5098a37be450b366f30cd9fdc1b40ac22f53bb9ba65834",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right foot",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [3] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "4046a27d54828cdcb3b3da429be67c922c6c50fdbdbf07b72318ad9456b7cacf",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "spine",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [4] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "2e52b300be728d0eff9860dfce1b5ab7b5435e530711f65be90722bb6ca2da3d",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "rightuplegroll",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [5] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "9f313364cdb47b084fe26f628413c8290d8072461428229aff7f5e369e137fd9",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "rightkneeup",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [6] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "b8f309fd71b096949aa3af376919b804a6be5561ff68b3c8e02de872de52f237",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right thigh",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [7] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "b2bb6754f4a99a7aa15d979ad9789bb1c43c60b118317b4b11dcd8ee5154efa1",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right calf",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [8] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "666cf02b2563ef8679e29d5dc3e30a11171db2e4d0c478763cc4cb71d1cb788d",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "skirt2",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [9] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "c98b5a343b486e497576467ad0488ac58a53df8a3d79ac107f7f44f5f782bc96",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left toe",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [10] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "53cb5de20a6c4e98bd1cf2926be05992ed8614e8769e0ad5b08f8b533d9932ed",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left thigh",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [11] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "be88f2dd09b1b2f9e9adeb71597626183e8b66c2f7fcaefcce0b013230dc63c0",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "leftkneeup",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [12] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "d34f777a91df5b0196a67ca75dcc46844ed4349f0f11eaf94b391b176330ccb9",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left calf",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [13] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "03b709b86d1b725e761bba7c6faf7b70aebb7939e94e0c8d1a9ca22f968954ed",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "spine 1",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [14] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "90cee824f44fd719a26a28cb9cae87f77c6077efd853054b3a19b871704dbaec",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left foot",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [15] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "eb9532687e22de6df67ca4b004216078be736c457f3a9962b633145b77fa7c3b",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "leftuplegroll",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [16] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "4a77a2091dc8de335031ec1689dadc798270c5ec1166a884cb99f04d05059b42",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right toe",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                },
                ["self"] = {
                    ["Skin"] = 0,
                    ["UniqueID"] = "87fc34fbefacc54d214d1e0f20147535caedfb0576a4c273f274a89c223d794c",
                    ["NoLighting"] = false,
                    ["AimPartName"] = "",
                    ["IgnoreZ"] = false,
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Materials"] = "",
                    ["Name"] = "",
                    ["LevelOfDetail"] = 0,
                    ["NoTextureFiltering"] = false,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["EyeAngles"] = false,
                    ["DrawOrder"] = 0,
                    ["TargetEntityUID"] = "",
                    ["Alpha"] = 1,
                    ["Material"] = "",
                    ["Invert"] = false,
                    ["ForceObjUrl"] = false,
                    ["Bone"] = "head",
                    ["Color"] = Vector(1, 1, 1),
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["BoneMerge"] = true,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["ClassName"] = "model2",
                    ["NoCulling"] = false,
                    ["Hide"] = false,
                    ["Brightness"] = 1,
                    ["Scale"] = Vector(1, 1, 1),
                    ["LegacyTransform"] = false,
                    ["EditorExpand"] = true,
                    ["Size"] = 0.1,
                    ["Translucent"] = false,
                    ["BlendMode"] = "",
                    ["ModelModifiers"] = "",
                    ["EyeTargetUID"] = "",
                    ["Model"] = "models/player/valley/zakuul/zakuul_knight.mdl",
                },
            },
            [6] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "1d9b9add559c1bb87e1806b23aa2917dd29952c5671b5d5bfecc8d854adeb96c",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "spine",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [7] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "d2b20fdfa42962abfa2047261886a37c23c0594b1cbdcb339099e51a40990e2c",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right calf",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [8] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "f4a00e05e899fc23dbf569580fc8db6939e4e645148fda81c6bcd6e262c09012",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right toe",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [9] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "8a60efb3d3bc33191770fff3d8c809e371d48c034af4de109f1d554a02ce061d",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "pelvis",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [10] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "1830a12d1072611297bfd5fb0b0ac79ded9239b856622047d91e5165985b7fa2",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left thigh",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [11] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "468be5e55241decda9f7972fbb0be61a1d105844098ff314ed8d46080d2e804f",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left toe",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
        },
        ["self"] = {
            ["DrawOrder"] = 0,
            ["UniqueID"] = "2685c63664ccdb07cac64b647ca6b79a5ffcec366ff189276b9fe61be47a3154",
            ["Notes"] = "",
            ["Hide"] = false,
            ["Name"] = "",
            ["TargetEntityUID"] = "",
            ["EditorExpand"] = true,
            ["OwnerName"] = "self",
            ["Duplicate"] = false,
            ["IsDisturbing"] = false,
            ["ModelTracker"] = "models/player/sith/pantoran.mdl",
            ["ClassTracker"] = "player",
            ["ClassName"] = "group",
        },
    },    
}
