ITEM.name = "Zakuul Black Knight gloves"
ITEM.description = ""
ITEM.outfitCategory = "gloves"
ITEM.uniqueID = "zakuul_black_knight_gloves"
ITEM.model = "models/player/valley/zakuul/zakuul_black.mdl"
ITEM.Base = "base_pacmmooutfit"

ITEM.attribRanges = {
	["str"] = {min = 1, max = 50},
	["stm"]  = {min = 1,  max = 50},
	["arm"]  = {min = 1,  max = 50},
	["end"] = {min = 1,  max = 50}
 }

ITEM.pacData = {
    [1] = {
        ["children"] = {
            [1] = {
                ["children"] = {
                    [1] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "c53448766aa3b95e6b9b4b3f7b1f320df686a35e1a19c475ab3753886e9271d5",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right forearm",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [2] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "d4fa21ea51f00f3c5b98031da22ecafc8c4269f08ef3370515d561031e7c28fc",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left forearm",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 100,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [3] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "b3db89466e1fb48ba129ed32517cacfd31d084695505b531ee308580e05ae7c1",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right hand",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0.0009765625, 0.19921875, 0.318359375),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 15.175,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [4] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["FollowAnglesOnly"] = false,
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "5ab886a88b6adf66261a0f0b24f38ce3927c18b8eea5dbdd1633524f13adbbb4",
                            ["TargetEntityUID"] = "",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "left hand",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(9.6049541298271e-07, -3.2580308914185, 7.2570760494273e-06),
                            ["Position"] = Vector(-0.0185546875, 0.146484375, -0.294921875),
                            ["AimPartUID"] = "",
                            ["Notes"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["EditorExpand"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Size"] = 11.3,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "bone3",
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                },
                ["self"] = {
                    ["Skin"] = 0,
                    ["UniqueID"] = "0062ce80976b1d2209b7aa27ada75f7934c3ddbace1a3c1fb17bb71e25606c44",
                    ["NoLighting"] = false,
                    ["AimPartName"] = "",
                    ["IgnoreZ"] = false,
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Materials"] = "",
                    ["Name"] = "",
                    ["LevelOfDetail"] = 0,
                    ["NoTextureFiltering"] = false,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["EyeAngles"] = false,
                    ["DrawOrder"] = 0,
                    ["TargetEntityUID"] = "",
                    ["Alpha"] = 1,
                    ["Material"] = "",
                    ["Invert"] = false,
                    ["ForceObjUrl"] = false,
                    ["Bone"] = "head",
                    ["Color"] = Vector(1, 1, 1),
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["BoneMerge"] = true,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["ClassName"] = "model2",
                    ["NoCulling"] = false,
                    ["Hide"] = false,
                    ["Brightness"] = 1,
                    ["Scale"] = Vector(1, 1, 1),
                    ["LegacyTransform"] = false,
                    ["EditorExpand"] = true,
                    ["Size"] = 0.1,
                    ["Translucent"] = false,
                    ["BlendMode"] = "",
                    ["ModelModifiers"] = "",
                    ["EyeTargetUID"] = "",
                    ["Model"] = "models/player/valley/zakuul/zakuul_black.mdl",
                },
            },
            [2] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "3a512121aa29024997e24065a2a565ced0f61fbafbe785626ffc351ec4fedf7a",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "right forearm",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
            [3] = {
                ["children"] = {
                },
                ["self"] = {
                    ["FollowAnglesOnly"] = false,
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "adca83ce976568d11206970877c3fea753797dae2e64c6cc627c27fcc4a00771",
                    ["TargetEntityUID"] = "",
                    ["AimPartName"] = "",
                    ["FollowPartUID"] = "",
                    ["Bone"] = "left forearm",
                    ["InvertHideMesh"] = false,
                    ["ScaleChildren"] = false,
                    ["MoveChildrenToOrigin"] = false,
                    ["Angles"] = Angle(0, 0, 0),
                    ["Position"] = Vector(0, 0, 0),
                    ["AimPartUID"] = "",
                    ["Notes"] = "",
                    ["Hide"] = false,
                    ["Name"] = "",
                    ["Scale"] = Vector(1, 1, 1),
                    ["EditorExpand"] = false,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["Size"] = 0.1,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["ClassName"] = "bone3",
                    ["EyeAngles"] = false,
                    ["HideMesh"] = false,
                },
            },
        },
        ["self"] = {
            ["DrawOrder"] = 0,
            ["UniqueID"] = "56130cbf7ae8b2a01e2557ba7abdc868c2f141e27ced3c473b4f44898921d9f4",
            ["Notes"] = "",
            ["Hide"] = false,
            ["Name"] = "",
            ["TargetEntityUID"] = "",
            ["EditorExpand"] = true,
            ["OwnerName"] = "self",
            ["Duplicate"] = false,
            ["IsDisturbing"] = false,
            ["ModelTracker"] = "models/player/sith/pantoran.mdl",
            ["ClassTracker"] = "player",
            ["ClassName"] = "group",
        },
    },
     
}
